<a href="https://colab.research.google.com/github/AditiAdhikari02/Digital-Ticketing-System/blob/main/intro_to_num_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Introduction to numpy


In [ ]:
# importing
import numpy as np

In [ ]:
# lets create an array
np.zeros(10)

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# create an array with different values
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7,  8,  9])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# multidimensional array
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
b = np.array ([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b [1, 1] = 50
b

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [ ]:
# random number generation
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
# random numbers following normal distribution
np.random.randn(5, 2)

array([[-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229],
       [-1.42121723, -0.1534952 ]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[15,  8],
       [17, 22],
       [73, 57],
       [90, 62],
       [83, 96]])

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a.std()

np.float64(1.4142135623730951)

In [ ]:
a.min()

np.int64(0)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.sum()

np.int64(10)